<?php

namespace Tm\TeambuilderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipeRepository extends EntityRepository
{
    public function getEquipeUtilisateurActuel($idUtilisateur)
    {
        $qb = $this->createQueryBuilder('e')
            ->where('u.id = :id ')
            ->setParameter('id', $idUtilisateur)
            ->join('e.utilisateur', 'u')
            ->addSelect('e');

        return $qb->getQuery()->getSingleResult();
    }

}
